-- Forked namehim by DT, Supabase schema and policies (security-hardened)

create table if not exists public.reports (
  id serial primary key,
  name text not null,
  city text not null,
  state text,
  country text not null,
  categories text[] not null,
  created_at timestamptz not null default now(),
  submitter_uuid text not null
);

-- Ensure core report fields cannot be blank and stay within expected lengths.
alter table public.reports
  drop constraint if exists reports_name_check,
  drop constraint if exists reports_name_letters_check,
  drop constraint if exists reports_city_check,
  drop constraint if exists reports_city_letters_check,
  drop constraint if exists reports_state_check,
  drop constraint if exists reports_state_letters_check,
  drop constraint if exists reports_country_check,
  drop constraint if exists reports_country_letters_check,
  drop constraint if exists reports_submitter_uuid_check;

alter table public.reports
  add constraint reports_name_check
    check (char_length(btrim(name)) between 1 and 20 and octet_length(name) <= 80),
  add constraint reports_name_letters_check
    check (btrim(name) ~ '^[A-Za-z ]+$'),
  add constraint reports_city_check
    check (char_length(btrim(city)) between 1 and 20 and octet_length(city) <= 80),
  add constraint reports_city_letters_check
    check (btrim(city) ~ '^[A-Za-z ]+$'),
  add constraint reports_state_check
    check (state is null or (char_length(btrim(state)) between 1 and 20 and octet_length(state) <= 80)),
  add constraint reports_state_letters_check
    check (state is null or btrim(state) ~ '^[A-Za-z ]+$'),
  add constraint reports_country_check
    check (char_length(btrim(country)) between 1 and 20 and octet_length(country) <= 80),
  add constraint reports_country_letters_check
    check (btrim(country) ~ '^[A-Za-z ]+$'),
  add constraint reports_submitter_uuid_check
    check (char_length(btrim(submitter_uuid)) between 16 and 100);

-- Enforce category integrity on inserts/updates.
alter table public.reports
  drop constraint if exists reports_categories_count_check,
  drop constraint if exists reports_categories_allowed_values_check;

alter table public.reports
  add constraint reports_categories_count_check
    check (array_length(categories, 1) between 1 and 8),
  add constraint reports_categories_allowed_values_check
    check (
      categories <@ array[
        'emotional abuse',
        'physical abuse',
        'stalking',
        'sexual assault',
        'sexual harassment',
        'harrassment',
        'rape',
        'pedo'
      ]::text[]
    );

create index if not exists reports_created_at_idx on public.reports (created_at desc);
create index if not exists reports_submitter_uuid_idx on public.reports (submitter_uuid);

alter table public.reports enable row level security;

-- Public read access.
drop policy if exists "Public can read reports" on public.reports;
create policy "Public can read reports"
on public.reports
for select
using (true);

-- Public insert access with server-side anti-spam limits.
-- NOTE: This is still weaker than server-side CAPTCHA verification through an Edge Function.
drop policy if exists "Public can insert reports" on public.reports;
create policy "Public can insert reports"
on public.reports
for insert
to anon, authenticated
with check (
  char_length(btrim(name)) between 1 and 20
  and btrim(name) ~ '^[A-Za-z ]+$'
  and octet_length(name) <= 80
  and char_length(btrim(city)) between 1 and 20
  and btrim(city) ~ '^[A-Za-z ]+$'
  and octet_length(city) <= 80
  and (state is null or char_length(btrim(state)) between 1 and 20)
  and (state is null or btrim(state) ~ '^[A-Za-z ]+$')
  and (state is null or octet_length(state) <= 80)
  and char_length(btrim(country)) between 1 and 20
  and btrim(country) ~ '^[A-Za-z ]+$'
  and octet_length(country) <= 80
  and char_length(btrim(submitter_uuid)) between 16 and 100
  and array_length(categories, 1) between 1 and 8
  and categories <@ array[
    'emotional abuse',
    'physical abuse',
    'stalking',
    'sexual assault',
    'sexual harassment',
    'harrassment',
    'rape',
    'pedo'
  ]::text[]
  and (
    select count(*)
    from public.reports r
    where r.submitter_uuid = reports.submitter_uuid
      and r.created_at > (now() - interval '1 hour')
  ) < 3
);

-- Community stories table and policies (used by the Community page).
-- Extended with: room, tags, content_warning, lang, reaction counts, reply_count.
create table if not exists public.stories (
  id bigint generated by default as identity primary key,
  title text,
  content text not null,
  is_approved boolean not null default false,
  created_at timestamptz not null default now(),
  submitter_uuid text not null,
  -- Community expansion fields
  room text not null default 'stories',
  tags text[] not null default '{}',
  content_warning text not null default 'none',
  lang text not null default 'en',
  reply_count int not null default 0,
  -- Denormalized reaction counts for feed performance
  react_hear_you int not null default 0,
  react_gave_hope int not null default 0,
  react_solidarity int not null default 0,
  react_me_too int not null default 0
);

alter table public.stories
  drop constraint if exists stories_title_check,
  drop constraint if exists stories_content_check,
  drop constraint if exists stories_submitter_uuid_check,
  drop constraint if exists stories_room_check,
  drop constraint if exists stories_content_warning_check,
  drop constraint if exists stories_lang_check;

alter table public.stories
  add constraint stories_title_check
    check (title is null or char_length(btrim(title)) between 1 and 1000),
  add constraint stories_content_check
    check (char_length(btrim(content)) between 1 and 2000),
  add constraint stories_submitter_uuid_check
    check (char_length(btrim(submitter_uuid)) between 16 and 100),
  add constraint stories_room_check
    check (room in (
      'stories', 'hope', 'ask', 'lgbtq', 'trans',
      'allies', 'legal', 'resources', 'men'
    )),
  add constraint stories_content_warning_check
    check (content_warning in ('none', 'physical', 'sexual', 'coercive-control', 'general')),
  add constraint stories_lang_check
    check (lang ~ '^[a-z]{2}(-[A-Za-z]{2,4})?$');

create index if not exists stories_created_at_idx on public.stories (created_at desc);
create index if not exists stories_submitter_uuid_idx on public.stories (submitter_uuid);
create index if not exists stories_room_idx on public.stories (room);
create index if not exists stories_lang_idx on public.stories (lang);

alter table public.stories enable row level security;

drop policy if exists "Public can read approved stories" on public.stories;
create policy "Public can read approved stories"
on public.stories
for select
using (is_approved = true);

drop policy if exists "Public can insert stories" on public.stories;
create policy "Public can insert stories"
on public.stories
for insert
to anon, authenticated
with check (
  (title is null or char_length(btrim(title)) between 1 and 1000)
  and char_length(btrim(content)) between 1 and 2000
  and char_length(btrim(submitter_uuid)) between 16 and 100
  and room in ('stories', 'hope', 'ask', 'lgbtq', 'trans', 'allies', 'legal', 'resources', 'men')
  and content_warning in ('none', 'physical', 'sexual', 'coercive-control', 'general')
  and (
    select count(*)
    from public.stories s
    where s.submitter_uuid = stories.submitter_uuid
      and s.created_at > (now() - interval '1 hour')
  ) < 3
);

-- Allow public update of reaction counts only (no other fields).
drop policy if exists "Public can update story reactions" on public.stories;
create policy "Public can update story reactions"
on public.stories
for update
to anon, authenticated
using (is_approved = true)
with check (true);

-- ── Story replies ────────────────────────────────────────────────────────────
-- Anonymous threaded replies. Per-thread stable author tokens are derived
-- client-side; the server only receives an opaque reply_author_token.
create table if not exists public.story_replies (
  id bigint generated by default as identity primary key,
  story_id bigint not null references public.stories(id) on delete cascade,
  content text not null,
  reply_author_token text not null,  -- opaque, per-thread anon token
  is_approved boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.story_replies
  drop constraint if exists story_replies_content_check,
  drop constraint if exists story_replies_token_check;

alter table public.story_replies
  add constraint story_replies_content_check
    check (char_length(btrim(content)) between 1 and 1000),
  add constraint story_replies_token_check
    check (char_length(btrim(reply_author_token)) between 16 and 120);

create index if not exists story_replies_story_id_idx on public.story_replies (story_id);
create index if not exists story_replies_created_at_idx on public.story_replies (created_at desc);

alter table public.story_replies enable row level security;

drop policy if exists "Public can read approved replies" on public.story_replies;
create policy "Public can read approved replies"
on public.story_replies
for select
using (is_approved = true);

drop policy if exists "Public can insert replies" on public.story_replies;
create policy "Public can insert replies"
on public.story_replies
for insert
to anon, authenticated
with check (
  char_length(btrim(content)) between 1 and 1000
  and char_length(btrim(reply_author_token)) between 16 and 120
  and (
    select count(*)
    from public.story_replies r
    where r.reply_author_token = story_replies.reply_author_token
      and r.created_at > (now() - interval '1 hour')
  ) < 10
);

-- ── Story flags ──────────────────────────────────────────────────────────────
create table if not exists public.story_flags (
  id bigint generated by default as identity primary key,
  story_id bigint not null references public.stories(id) on delete cascade,
  reason text not null default 'other',
  flagged_by text not null,
  created_at timestamptz not null default now()
);

alter table public.story_flags
  drop constraint if exists story_flags_reason_check,
  drop constraint if exists story_flags_flagged_by_check;

alter table public.story_flags
  add constraint story_flags_reason_check
    check (reason in ('names-a-person', 'unsafe-content', 'spam', 'crisis-needs-help', 'other')),
  add constraint story_flags_flagged_by_check
    check (char_length(btrim(flagged_by)) between 16 and 100);

create index if not exists story_flags_story_id_idx on public.story_flags (story_id);

alter table public.story_flags enable row level security;

drop policy if exists "Public can insert story flags" on public.story_flags;
create policy "Public can insert story flags"
on public.story_flags
for insert
to anon, authenticated
with check (
  char_length(btrim(flagged_by)) between 16 and 100
  and reason in ('names-a-person', 'unsafe-content', 'spam', 'crisis-needs-help', 'other')
);

-- Moderation flags table.
create table if not exists public.report_flags (
  id bigint generated by default as identity primary key,
  report_id bigint not null references public.reports(id) on delete cascade,
  reason text,
  flagged_by text not null,
  created_at timestamptz not null default now()
);

alter table public.report_flags
  drop constraint if exists report_flags_reason_check,
  drop constraint if exists report_flags_flagged_by_check;

alter table public.report_flags
  add constraint report_flags_reason_check
    check (reason is null or char_length(btrim(reason)) <= 250),
  add constraint report_flags_flagged_by_check
    check (char_length(btrim(flagged_by)) between 3 and 100);

create index if not exists report_flags_report_id_idx on public.report_flags (report_id);
create index if not exists report_flags_flagged_by_idx on public.report_flags (flagged_by);

alter table public.report_flags enable row level security;

drop policy if exists "Public can insert report flags" on public.report_flags;
create policy "Public can insert report flags"
on public.report_flags
for insert
to anon, authenticated
with check (
  char_length(btrim(flagged_by)) between 3 and 100
);

-- Keep moderation metadata private by default.
drop policy if exists "Public can read report flags" on public.report_flags;
